config/routes.rb
Kicker::Application.routes.draw do
  resources :college_wish_lists

  resources :references

  resources :awards

  resources :bios

  resources :image_sliders

  devise_for :users

  get "static_pages/admin"
  get "static_pages/landing"
  get "static_pages/kicker_list"
  resources :point_after_attempts

  resources :field_goals

  resources :punts

  resources :kickoffs

  resources :highlights

  devise_scope :user do
    get 'register', to: "devise/registrations#new", as: :register
    get 'login', to: "devise/sessions#new", as: :login
    get 'logout', to: "devise/sessions#destroy", as: :logout
  end

  root :to => 'static_pages#landing'

end

app/models/bio.rb
class Bio < ActiveRecord::Base
  attr_accessible :ACT_score, :GPA, :SAT_score, :bench_press, :bio_content, :clearing_house_cleared, :college_credits_earned, :email, :first_name, :graduation_year, :height, :image_link, :last_name, :phone, :primary_kicking_coach, :primary_kicking_coach_email, :primary_kicking_coach_phone, :school_city, :school_name, :school_phone, :school_fax, :school_counselor_name, :school_counselor_phone, :school_counselor_email, :school_state, :school_street, :school_url, :school_zip, :sprint_40_time, :squat, :team_head_coach, :team_head_coach_email, :team_head_coach_phone, :team_special_teams_coach, :team_special_teams_coach_phone, :team_special_teams_coach_email, :vertical_jump, :weight
end

app/controllers/bios_controller.rb
class BiosController < ApplicationController
  # GET /bios
  # GET /bios.json
  def index
    @bios = Bio.all

    @awards = Award.order('date DESC')
    @references = Reference.all
    @field_goals = FieldGoal.all
    @total_field_goals = FieldGoal.count(:conditions => { :is_good => true }) * 3
    @field_goal_long = FieldGoal.maximum('distance', :conditions => {:is_good => true})

    @field_goal_count = FieldGoal.count('is_good')
    @field_goals_made = FieldGoal.count(:conditions => { :is_good => true })
    @field_goal_percent = (@field_goals_made.to_f / @field_goal_count.to_f * 100).round(1)


    @point_after_attempts = PointAfterAttempt.all
    @total_pats = PointAfterAttempt.count(:conditions => { :is_good => true })

    @kickoffs = Kickoff.all
    @total_kickoff_yards = Kickoff.sum('distance')
    @kickoff_long = Kickoff.maximum('distance')
    @total_kicks = Kickoff.count('distance')
    @touchback_totals = Kickoff.count(:conditions => "distance > 60")
    @touchback_percentage = (@touchback_totals.to_f / @total_kicks.to_f * 100).round(1)

    @kickoff_avg = Integer(Kickoff.average('distance'))


    @punts = Punt.all
    @punt_long = Punt.maximum('distance')

    @total_points = Integer(@total_field_goals.to_f + @total_pats.to_f)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bios }
    end
  end

  # GET /bios/1
  # GET /bios/1.json
  def show
    @bio = Bio.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bio }
    end
  end

  # GET /bios/new
  # GET /bios/new.json
  def new
    @bio = Bio.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bio }
    end
  end

  # GET /bios/1/edit
  def edit
    @bio = Bio.find(params[:id])
  end

  # POST /bios
  # POST /bios.json
  def create
    @bio = Bio.new(params[:bio])

    respond_to do |format|
      if @bio.save
        format.html { redirect_to @bio, notice: 'Bio was successfully created.' }
        format.json { render json: @bio, status: :created, location: @bio }
      else
        format.html { render action: "new" }
        format.json { render json: @bio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bios/1
  # PUT /bios/1.json
  def update
    @bio = Bio.find(params[:id])

    respond_to do |format|
      if @bio.update_attributes(params[:bio])
        format.html { redirect_to @bio, notice: 'Bio was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bios/1
  # DELETE /bios/1.json
  def destroy
    @bio = Bio.find(params[:id])
    @bio.destroy

    respond_to do |format|
      format.html { redirect_to bios_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/bios_helper.rb
module BiosHelper
end

app/views/bios/_form.html.erb
<% if user_signed_in? %>
<%= simple_form_for(@bio) do |f| %>
  <%= f.error_notification %>

    <dl class="tabs" data-tab>
      <dd class="active"><a href="#panel2-1">Personal Info</a></dd>
      <dd><a href="#panel2-2">Physical / Strength</a></dd>
      <dd><a href="#panel2-3">School &amp; Academics</a></dd>
    </dl>
    <div class="tabs-content">
      <div class="content active" id="panel2-1">
        <div class="row">
            <div class="large-12 columns"><h2>Personal</h2></div>
            <div class="large-5 columns"><%= f.input :first_name %></div>
            <div class="large-5 columns"><%= f.input :last_name %></div>
            <div class="large-2 columns"><%= f.input :graduation_year %></div>
            <div class="large-4 columns"><%= f.input :image_link %></div>
            <div class="large-4 columns"><%= f.input :email %></div>
            <div class="large-4 columns"><%= f.input :phone %></div>
            <div class="large-12 columns"><%= f.input :bio_content %></div>
        </div>
      </div>
      <div class="content" id="panel2-2">
        <div class="row">
            <div class="large-12 columns"><h2>Physical</h2></div>
            <div class="large-3 columns"><%= f.input :height, label: 'Height (inches)' %></div>
            <div class="large-3 columns"><%= f.input :weight %></div>
            <div class="large-3 columns"><%= f.input :sprint_40_time, label: "40yd dash time" %></div>
            <div class="large-3 columns"><%= f.input :vertical_jump, label: "Vertical Jump (inches)" %></div>
            <div class="large-6 columns"><%= f.input :bench_press %></div>
            <div class="large-6 columns"><%= f.input :squat, label: "Leg Press" %></div>
        </div>   
      </div>
      <div class="content" id="panel2-3">
        <div class="row">
            <div class="large-12 columns"><h2>Academics</h2></div>
            <div class="large-3 columns"><%= f.input :GPA, label: "GPA" %></div>
            <div class="large-3 columns"><%= f.input :SAT_score, label: "SAT Score" %></div>
            <div class="large-3 columns"><%= f.input :ACT_score, label: "ACT Score" %></div>
            <div class="large-3 columns"><%= f.input :college_credits_earned %></div>
            <div class="large-12 columns"><%= f.input :clearing_house_cleared, label: "Clearing house cleared?" %></div>
            <div class="large-12 columns"><h2>School Information / Location</h2></div>
            <div class="large-4 columns"><%= f.input :school_name %></div>
            <div class="large-2 columns"><%= f.input :school_phone %></div>
            <div class="large-2 columns"><%= f.input :school_fax %></div>
            <div class="large-4 columns"><%= f.input :school_url %></div>
            <div class="large-4 columns"><%= f.input :school_street, label: "Street" %></div>
            <div class="large-4 columns"><%= f.input :school_city , label: "City" %></div>
            <div class="large-2 columns"><%= f.input :school_state, label: "State", collection: us_states %></div>
            <div class="large-2 columns"><%= f.input :school_zip, label: "Zip" %></div>
        </div> 
      </div>


  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>
<% else %>
<p class="label alert">You must be logged in to add or edit Field Goals.</p>
<% end %>

app/views/bios/edit.html.erb
<div class="row">
	<div class="large-12 columns">
		<h1>Editing Bio</h1>
		<%= render 'form' %>
	</div>
</div>

<div class="row">
	<div class="large-12 columns">
		<%= link_to 'Show', @bio, :class => "button secondary" %>
		<%= link_to 'Back', bios_path, :class => "button secondary"  %>
	</div>
</div>

app/views/bios/index.html.erb
<% provide(:title, kicker_name + " | Bio") %>
<% @bios.each do |bio| %>
    <div class="row">
        <div class="large-11 medium-11 columns">
            <h1><%= bio.first_name %> <%= bio.last_name %> <small>Bio</small></h1>
        </div>
        <div class="large-1 medium-1 columns">
            <a href="#" class="button expand" data-reveal-id="followModal"><i class="fa fa-star"></i></a>
            <div id="followModal" class="reveal-modal small" data-reveal>
              <h2>Follow <%= bio.first_name %> <%= bio.last_name %></h2>
              <p>GPA changes, SAT changes, highlight updates, new awards, significant changes to stats, etc.</p>

              <a class="close-reveal-modal">&#215;</a>
            </div>
        </div>
    </div>
    <%= render("/shared/sub-nav") %>
    <div class="row">
        <div class="large-4 medium-6 columns text-center">
            <img src="<%= bio.image_link %>" class="img-responsive">
        </div>
        <div class="large-8 medium-6 columns">
            <table>
                <thead>
                    <tr>
                        <th>Category</th>
                        <th>Result</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>GPA</td>
                        <td><%= bio.GPA %></td>
                    </tr>
                    <tr>
                        <td>ACT</td>
                        <td><%= bio.ACT_score %></td>
                    </tr>
                    <tr>
                        <td>Graduation Year</td>
                        <td><%= bio.graduation_year %></td>
                    </tr>
                    <tr>
                        <td>SAT</td>
                        <td><%= bio.SAT_score %></td>
                    </tr>
                    <tr>
                        <td>College Credits</td>
                        <td><%= bio.college_credits_earned %></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="row hide-for-small-only">
        <div class="large-12 columns">
            <h2><i class="fa fa-bar-chart-o"></i> Stats</h2>
            <ul class="medium-block-grid-6 large-block-grid-6 text-center">
                <li>
                    <h4>Height</h4>
                    <%= bio.height %>"
                </li>
                <li>
                    <h4>Weight</h4>
                    <%= bio.weight %>lbs.
                </li>
                <li>
                    <h4>40yd Dash</h4>
                    <%= bio.sprint_40_time %>secs
                </li>
                <li>
                    <h4>Vertical</h4>
                    <%= bio.vertical_jump %>"
                </li>
                <li>
                    <h4>Leg Press</h4>
                    <%= bio.squat %>lbs.
                </li>
                <li>
                    <h4>Bench</h4>
                    <%= bio.bench_press %>lbs.
                </li>  
            </ul>
        </div>          
    </div>
    <div class="row text-center">
        <div class="large-3 medium-6 columns">
            <div class="panel">
                <p><strong>Total Points:</strong> </p>
                <h1><%= @total_points %></h1>
                <p>PATs: <%= @total_pats %> -  FGs: <%= @total_field_goals %></p>
            </div>
        </div>
        <div class="large-3 medium-6 columns">
            <div class="panel">
                <p><strong>Field Goal Long:</strong></p>
                <h1><%= @field_goal_long %></h1>
                <p>FG Success: <%= @field_goal_percent %>%</p>
            </div>
        </div>
        <div class="large-3 medium-6 columns">
            <div class="panel">
                <p><strong>Kickoff Long:</strong></p>
                <h1><%= @kickoff_long %></h1>
                <p>Avg KO: <%= @kickoff_avg %>yds</p>
            </div>
        </div>
        <div class="large-3 medium-6 columns">
            <div class="panel">
                <p><strong>Total Kickoff Yards:</strong></p>
                <h1><%= @total_kickoff_yards %></h1>
                <p>Touchbacks: <%= @touchback_percentage %>%</p>
            </div>
        </div>
        <div class="large-12 columns">
            <hr>
        </div>
    </div>
    <div class="row">
        <div class="large-10 large-centered columns">
             <strong>Bio:</strong> <%= bio.bio_content %>
        </div>
        <div class="large-12 columns">
            <hr>
        </div>
    </div>
    <div class="row">
      <div class="large-12 columns">
        <h2><i class="fa fa-trophy"></i> Honors &amp; Awards</h2>
        <table>
          <thead>
              <tr>
                <th>Date</th>
                <th>Award name</th>
                <% if user_signed_in? %>
                <th></th>
                <th></th>
                <% end %>
              </tr>
          </thead>
          <tbody>
              <% @awards.each do |award| %>
                <tr>
                  <td><%= l(award.date) %></td>
                  <td><%= award.award_name %></td>
                  <% if user_signed_in? %>
                  <td><%= link_to raw('<i class="fa fa-pencil"></i>'), edit_award_path(award), :class=> "button tiny expand" %></td>
                  <td><%= link_to raw('<i class="fa fa-times-circle"></i>'), award, method: :delete, data: { confirm: 'Are you sure?' }, :class=> "button tiny expand" %></td>
                  <% end %>
                </tr>
              <% end %>
          </tbody>
        </table>
            <% if user_signed_in? %>
            <%= link_to 'New Award', new_award_path, :class => "button secondary" %>
            <% end %>
      </div>
    </div>
    <div class="row">
        <div class="large-12 columns">
            <h2><i class="fa fa-apple"></i> School Contact Info</h2>

            <div class="panel">
                <div class="row">
                    <div class="large-4 medium-4 columns">
                        <div class="fn"><strong><%= bio.school_name %></strong></div>
                        <div class="street-address"><%= bio.school_street %></div>
                        <div>
                            <span class="locality"><%= bio.school_city %></span>, <span class="state"><%= bio.school_state %></span>, <span class="zip"><%= bio.school_zip %></span>
                        </div>
                    </div>
                    <div class="large-6 medium-6 columns">
                        <p>
                            <strong>Phone:</strong> <a href="tel:<%= bio.school_phone %>"><%= bio.school_phone %></a><br>
                            <strong>Fax:</strong>  <%= bio.school_fax %>
                        </p>
                    </div>
                    <div class="large-2 medium-2 columns">
                        <a href="<%= bio.school_url %>" class="button expand">Website</a>
                        <a href="https://www.google.com/maps/preview#!q=<%= bio.school_street %>%2C+<%= bio.school_city %>%2C+<%= bio.school_state %>" target="_blank" class="button expand show-for-small-only">Directions</a>
                    </div>
                </div>
                <div class="row show-for-medium-up">
                    <div class="large-12 columns">
                        <hr>
                        <iframe src="https://www.google.com/maps/embed?pb=!1m5!3m3!1m2!1s0x89e653629c38db6d%3A0x929ea2da73fa2973!2s<%= bio.school_street %>%2C+<%= bio.school_city %>%2C+<%= bio.school_state %>%2C+<%= bio.school_zip %>!5e0!3m2!1sen!2sus!4v1387244587724" width="100%" height="200" frameborder="0" style="border:0"></iframe>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="large-12 columns">
            <h2><i class="fa fa-users"></i> References</h2>
            <table>
              <thead>
                  <tr>
                    <th>Name</th>
                    <th>Title</th>
                    <th>Email</th>
                    <th>Phone</th>
                    <% if user_signed_in? %>
                    <th></th>
                    <th></th>
                    <% end %>
                  </tr>
              </thead>

              <tbody>
                  <% @references.each do |reference| %>
                    <tr>
                      <td><%= reference.reference_name %></td>
                      <td><%= reference.reference_title %></td>
                      <td><a href="mailto:<%= reference.reference_email %>"><%= reference.reference_email %></a></td>
                      <td><a href="tel:<%= reference.reference_phone %>"><%= reference.reference_phone %></a></td>
                      <% if user_signed_in? %>
                      <td><%= link_to raw('<i class="fa fa-pencil"></i>'), edit_reference_path(reference), :class=> "button tiny expand" %></td>
                      <td><%= link_to raw('<i class="fa fa-times-circle"></i>'), reference, method: :delete, data: { confirm: 'Are you sure?' }, :class=> "button tiny expand" %></td>
                      <% end %>
                    </tr>
              </tbody>
            <% end %>
            </table>
            <% if user_signed_in? %>
            <%= link_to 'New Reference', new_reference_path, :class=> "button secondary" %>
            <% end %>
        </div>
    </div>
    <% if user_signed_in? %>
        <div class="row">
            <div class="large-12 columns">
                <%= link_to raw('<i class="fa fa-pencil"></i>'), edit_bio_path(bio), :class => "button"  %>
            </div>
        </div>
    <% end %>
<% end %>

app/views/bios/new.html.erb
<div class="row">
	<div class="large-12 columns">
		<h1>Enter Bio</h1>
		<%= render 'form' %>
	</div>
</div>

<div class="row">
	<div class="large-12 columns"><%= link_to 'Back', bios_path, :class=> "button secondary" %></div>
</div>

app/views/bios/show.html.erb
<div class="row">
  <div class="large-12 columns">
    <div class="panel">
      <h1>Bio <small>Updated</small></h1>
      <p>
        <b>First name:</b>
        <%= @bio.first_name %>
      </p>

      <p>
        <b>Last name:</b>
        <%= @bio.last_name %>
      </p>

      <p>
        <b>Email:</b>
        <%= @bio.email %>
      </p>

      <p>
        <b>Phone:</b>
        <%= @bio.phone %>
      </p>

      <p>
        <b>Bio content:</b>
        <%= @bio.bio_content %>
      </p>

      <p>
        <b>Graduation year:</b>
        <%= @bio.graduation_year %>
      </p>

      <p>
        <b>Height:</b>
        <%= @bio.height %>
      </p>

      <p>
        <b>Weight:</b>
        <%= @bio.weight %>
      </p>

      <p>
        <b>Sprint 40 time:</b>
        <%= @bio.sprint_40_time %>
      </p>

      <p>
        <b>Vertical jump:</b>
        <%= @bio.vertical_jump %>
      </p>

      <p>
        <b>Bench press:</b>
        <%= @bio.bench_press %>
      </p>

      <p>
        <b>Squat:</b>
        <%= @bio.squat %>
      </p>

      <p>
        <b>Gpa:</b>
        <%= @bio.GPA %>
      </p>

      <p>
        <b>Sat score:</b>
        <%= @bio.SAT_score %>
      </p>

      <p>
        <b>Act score:</b>
        <%= @bio.ACT_score %>
      </p>

      <p>
        <b>College credits earned:</b>
        <%= @bio.college_credits_earned %>
      </p>

      <p>
        <b>Image link:</b>
        <%= @bio.image_link %>
      </p>

      <p>
        <b>School name:</b>
        <%= @bio.school_name %>
      </p>

      <p>
        <b>School url:</b>
        <%= @bio.school_url %>
      </p>

      <p>
        <b>School street:</b>
        <%= @bio.school_street %>
      </p>

      <p>
        <b>School city:</b>
        <%= @bio.school_city %>
      </p>

      <p>
        <b>School state:</b>
        <%= @bio.school_state %>
      </p>

      <p>
        <b>School zip:</b>
        <%= @bio.school_zip %>
      </p>

      <p>
        <b>Team head coach:</b>
        <%= @bio.team_head_coach %>
      </p>

      <p>
        <b>Team head coach phone:</b>
        <%= @bio.team_head_coach_phone %>
      </p>

      <p>
        <b>Team head coach email:</b>
        <%= @bio.team_head_coach_email %>
      </p>

      <p>
        <b>Team special teams coach:</b>
        <%= @bio.team_special_teams_coach %>
      </p>

      <p>
        <b>Primary kicking coach:</b>
        <%= @bio.primary_kicking_coach %>
      </p>

      <p>
        <b>Clearing house cleared:</b>
        <%= @bio.clearing_house_cleared %>
      </p>
    </div>
    <%= link_to 'Edit', edit_bio_path(@bio), :class=> "button" %>
    <%= link_to 'Back', bios_path, :class=> "button"  %>
  </div>
</div>