config/routes.rb
Kicker::Application.routes.draw do
  resources :college_wish_lists

  resources :references

  resources :awards

  resources :bios

  resources :image_sliders

  devise_for :users

  get "static_pages/admin"
  get "static_pages/landing"
  get "static_pages/kicker_list"
  resources :point_after_attempts

  resources :field_goals

  resources :punts

  resources :kickoffs

  resources :highlights

  devise_scope :user do
    get 'register', to: "devise/registrations#new", as: :register
    get 'login', to: "devise/sessions#new", as: :login
    get 'logout', to: "devise/sessions#destroy", as: :logout
  end

  root :to => 'static_pages#landing'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def admin
  	@awards = Award.order(:date)
  	@college_wish_lists = CollegeWishList.all
  	@field_goals = FieldGoal.order(:date)
  	@college_wish_lists = CollegeWishList.all
  	@highlights = Highlight.order('id ASC')
  	@kickoffs = Kickoff.order(:date)
  	@point_after_attempts = PointAfterAttempt.order(:date)
  	@punts = Punt.order(:date)
  	@references = Reference.all
  	@bios = Bio.all
  	respond_to do |format|
  	  format.html # index.html.erb
  	  format.json { render json: @awards }
  	end

  end
  def landing
    @image_sliders = ImageSlider.all
  end
  def kicker_list
    @bios = Bio.all
  end
end

app/views/static_pages/home.html.erb
<% provide(:title, kicker_name + " | Kicker") %>
<div class="hide-for-small-only">
	<ul class="example-orbit" data-orbit>
		<% @image_sliders.each do |image_slider| %>
			<li>
			  <img src="<%= image_slider.image_link %>" class="img-responsive" alt="<%= image_slider.alt_tag %>">
			  <div class="orbit-caption">
			    <%= image_slider.caption %>
			  </div>
			</li>
		<% end %>
	</ul>
</div>
<div class="show-for-small-only">
	<% @bios.each do |bio| %>
		<img src="<%= bio.image_link %>" class="img-responsive">
	<% end %>
</div>
<div class="row">
	<div class="large-12 columns text-center">
		<h1><%= kicker_name %> <br class="show-for-small-only"><small>Kicking Prospect</small></h1>
	</div>
</div>
<div class="row text-center">
	<div class="large-3 medium-6 columns">
		<div class="panel">
			<p><strong>Total Points:</strong> </p>
			<h1><%= @total_points %></h1>
			<p>PATs: <%= @total_pats %> -  FGs: <%= @total_field_goals %></p>
		</div>
	</div>
	<div class="large-3 medium-6 columns">
		<div class="panel">
			<p><strong>Field Goal Long:</strong></p>
			<h1><%= @field_goal_long %></h1>
			<p>FG Success: <%= @field_goal_percent %>%</p>
		</div>
	</div>
	<div class="large-3 medium-6 columns">
		<div class="panel">
			<p><strong>Kickoff Long:</strong></p>
			<h1><%= @kickoff_long %></h1>
			<p>Avg KO: <%= @kickoff_avg %>yds</p>
		</div>
	</div>
	<div class="large-3 medium-6 columns">
		<div class="panel">
			<p><strong>Total Kickoff Yards:</strong></p>
			<h1><%= @total_kickoff_yards %></h1>
			<p>Touchbacks: <%= @touchback_percentage %>%</p>
		</div>
	</div>
</div>

app/views/static_pages/kicker_list.html.erb
<% provide(:title, "iKick.it, Kicker List") %>
<div class="row">
	<div class="large-11 columns">
		<h1>Kicker List</h1>
	</div>
	<div class="large-1 columns">
		<a href="#" class="button expand" data-reveal-id="searchModal"><i class="fa fa-search"></i></a>
		<div id="searchModal" class="reveal-modal small" data-reveal>
		  <h2>Search for Kicker By:</h2>
		  <ul class="inline-list">
		  	<li>TB%</li>
		  	<li>FG%</li>
		  	<li>Punt Avg.</li>
		  	<li>SAT Score</li>
		  	<li>GPA Score</li>
		  </ul>

		  <a class="close-reveal-modal">&#215;</a>
		</div>
	</div>
</div>
<div class="row">
	<div class="large-4 columns">
		<h2>Kickoffs <small>Top 2</small></h2>
			<div class="row">
				<div class="large-6 columns"><%= link_to image_tag("https://dl.dropboxusercontent.com/u/39806773/kicker/chase-bio-pic.jpg"), bios_path, :class=> "img-responsive" %></div>
				<div class="large-6 columns">
					<p><strong><%= kicker_name %></strong><br>TB Avg: 99%</p>
					<%= link_to "Bio", bios_path, :class=> "button tiny" %>
				</div>
			</div>
			<div class="row">
				<div class="large-12 columns">
					<hr>
				</div>
				<div class="large-6 columns"><%= link_to image_tag("https://dl.dropboxusercontent.com/u/39806773/kicker/chase-bio-pic.jpg"), bios_path, :class=> "img-responsive" %></div>
				<div class="large-6 columns">
					<p><strong><%= kicker_name %></strong><br>TB Avg: 99%</p>
					<%= link_to "Bio", bios_path, :class=> "button tiny" %>
				</div>
			</div>
	</div>
	<div class="large-4 columns">
		<h2>Field Goals <small>Top 2</small></h2>
		<div class="row">
				<div class="large-6 columns">
					<%= link_to image_tag("https://dl.dropboxusercontent.com/u/39806773/kicker/chase-bio-pic.jpg"), bios_path, :class=> "img-responsive" %>
					</div>
				<div class="large-6 columns">
					<p><strong><%= kicker_name %></strong><br>FG Avg: 99%</p>
					<%= link_to "Bio", bios_path, :class=> "button tiny" %>
				</div>
			</div>
			<div class="row">
				<div class="large-12 columns">
					<hr>
				</div>
				<div class="large-6 columns"><%= link_to image_tag("https://dl.dropboxusercontent.com/u/39806773/kicker/chase-bio-pic.jpg"), bios_path, :class=> "img-responsive" %></div>
				<div class="large-6 columns">
					<p><strong><%= kicker_name %></strong><br>FG Avg: 99%</p>
					<%= link_to "Bio", bios_path, :class=> "button tiny" %>
				</div>
			</div>
	</div>
	<div class="large-4 columns">
		<h2>Punts <small>Top 2</small></h2>
		<div class="row">
			<div class="large-6 columns"><%= link_to image_tag("https://dl.dropboxusercontent.com/u/39806773/kicker/chase-bio-pic.jpg"), bios_path, :class=> "img-responsive" %></div>
			<div class="large-6 columns">
				<p><strong><%= kicker_name %></strong><br>Punt Avg: 49yds</p>
					<%= link_to "Bio", bios_path, :class=> "button tiny" %>
			</div>
		</div>
		<div class="row">
			<div class="large-12 columns">
				<hr>
			</div>
			<div class="large-6 columns"><%= link_to image_tag("https://dl.dropboxusercontent.com/u/39806773/kicker/chase-bio-pic.jpg"), bios_path, :class=> "img-responsive" %></div>
			<div class="large-6 columns">
				<p><strong><%= kicker_name %></strong><br>Punt Avg: 49yds</p>
					<%= link_to "Bio", bios_path, :class=> "button tiny" %>
			</div>
		</div>
	</div>
</div>

app/views/static_pages/landing.html.erb
<% provide(:title, "iKick.it, Because I can!") %>
<div class="hide-for-small-only">
    <ul class="example-orbit" data-orbit>
        <% @image_sliders.each do |image_slider| %>
            <li>
              <img src="<%= image_slider.image_link %>" class="img-responsive" alt="<%= image_slider.alt_tag %>">
              <div class="orbit-caption">
                <%= image_slider.caption %>
              </div>
            </li>
        <% end %>
    </ul>
</div>
<div class="row">
	<div class="large-12 columns hide-for-small-only">
		<h1><%= app_name %> <small>for college bound kickers</small></h1>
	</div>
	<div class="large-12 columns text-center show-for-small-only">
		<h1><%= app_name %></h1>
	</div>
	<div class="large-6 medium-6 columns text-center">
		<img src="https://dl.dropboxusercontent.com/u/39806773/kicker/landing-2.jpg" class="img-responsive" alt="Some tag">
	</div>
	<div class="large-6 medium-6 columns">
		<h1>Get Started</h1>
		<p><%= app_name %> is absolutely free to kickers and recruiting coaches. No strings attached. Simple easy to get started.</p>
		<div class="row">
			<div class="large-6 columns">
				<%= link_to raw('<i class="fa fa-pencil"></i> Register Now'), register_path, :class=> "button expand large" %>
			</div>
			<div class="large-6 columns">
				<%= link_to raw('<i class="fa fa-list"></i> Search for Kickers'), static_pages_kicker_list_path, :class=> "button secondary expand large"  %>
			</div>
			<div class="large-12 columns">
				<ul class="inline-list">
					<li><%= link_to raw('<i class="fa fa-unlock"></i> Login'), login_path %> </li>
					<li><a href="#"><i class="fa fa-info"></i> Site Info</a></li>
				</ul>
			</div>
		</div>
	</div>

</div>