config/routes.rb
Kicker::Application.routes.draw do
  resources :college_wish_lists

  resources :references

  resources :awards

  resources :bios

  resources :image_sliders

  devise_for :users

  get "static_pages/admin"
  get "static_pages/landing"
  get "static_pages/kicker_list"
  resources :point_after_attempts

  resources :field_goals

  resources :punts

  resources :kickoffs

  resources :highlights

  devise_scope :user do
    get 'register', to: "devise/registrations#new", as: :register
    get 'login', to: "devise/sessions#new", as: :login
    get 'logout', to: "devise/sessions#destroy", as: :logout
  end

  root :to => 'static_pages#landing'

end

app/models/award.rb
class Award < ActiveRecord::Base
  attr_accessible :award_name, :date
end

app/controllers/awards_controller.rb
class AwardsController < ApplicationController
  # GET /awards
  # GET /awards.json
  def index
    @awards = Award.order(:date)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @awards }
    end
  end

  # GET /awards/1
  # GET /awards/1.json
  def show
    @award = Award.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @award }
    end
  end

  # GET /awards/new
  # GET /awards/new.json
  def new
    @award = Award.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @award }
    end
  end

  # GET /awards/1/edit
  def edit
    @award = Award.find(params[:id])
  end

  # POST /awards
  # POST /awards.json
  def create
    @award = Award.new(params[:award])

    respond_to do |format|
      if @award.save
        format.html { redirect_to @award, notice: 'Award was successfully created.' }
        format.json { render json: @award, status: :created, location: @award }
      else
        format.html { render action: "new" }
        format.json { render json: @award.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /awards/1
  # PUT /awards/1.json
  def update
    @award = Award.find(params[:id])

    respond_to do |format|
      if @award.update_attributes(params[:award])
        format.html { redirect_to @award, notice: 'Award was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @award.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /awards/1
  # DELETE /awards/1.json
  def destroy
    @award = Award.find(params[:id])
    @award.destroy

    respond_to do |format|
      format.html { redirect_to awards_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/awards_helper.rb
module AwardsHelper
end

app/views/awards/_form.html.erb
<% if user_signed_in? %>
<%= simple_form_for(@award) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  	<%= f.input :date %>
    <%= f.input :award_name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>
<% else %>
<p class="label alert">You must be logged in to add or edit Awards.</p>
<% end %>

app/views/awards/edit.html.erb
<div class="row">
	<div class="large-6 medium-8 columns medium-centered large-centered">
		<div class="panel">
			<h1>Edit <small>Award</small></h1>
			<%= render 'form' %>
		</div>
		<%= link_to 'Show', @award, :class=> "button secondary"  %>
		<%= link_to 'Back to Bios', bios_path, :class=> "button secondary"  %>
	</div>
</div>

app/views/awards/index.html.erb
<div class="row">
  <div class="large-10 medium-10 columns">
    <h1>Awards</h1>
  </div>
  <div class="large-2 medium-2 columns">
    <% if user_signed_in? %>
    <%= link_to 'New Award', new_award_path, :class => "button expand" %>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="large-12 columns">
    <table>
      <tr>
        <th>Date</th>
        <th>Award name</th>
        <% if user_signed_in? %>
        <th></th>
        <th></th>
        <% end %>
      </tr>
    
    <% @awards.each do |award| %>
      <tr>
        <td><%= l(award.date) %></td>
        <td><%= award.award_name %></td>
        <% if user_signed_in? %>
        <td><%= link_to raw('<i class="fa fa-pencil"></i>'), edit_award_path(award), :class => "button tiny expand" %></td>
        <td><%= link_to raw('<i class="fa fa-times-circle"></i>'), award, method: :delete, data: { confirm: 'Are you sure?' }, :class => "button tiny expand"  %></td>
        <% end %>
      </tr>
    <% end %>
    </table>
        <% if user_signed_in? %>
        <%= link_to 'New Award', new_award_path, :class => "button secondary" %>
        <% end %>
  </div>
</div>

app/views/awards/new.html.erb
<div class="row">
	<div class="large-6 medium-8 columns medium-centered large-centered">
		<div class="panel">
			<h1>Enter <small>Award</small></h1>
			<%= render 'form' %>
		</div>
		<%= link_to 'Back', awards_path, :class=> "button secondary" %>
	</div>
</div>

app/views/awards/show.html.erb
<div class="row">
	<div class="large-12 columns">
		<div class="panel">
			<h1>Award <small>Submitted</small></h1>
			<p><%= @award.award_name %></p>
			<%= link_to 'Edit', edit_award_path(@award), :class=> "button secondary" %>
			<%= link_to 'Back', awards_path, :class=> "button secondary" %>
		</div>
	</div>
</div>