config/routes.rb
Kicker::Application.routes.draw do
  resources :college_wish_lists

  resources :references

  resources :awards

  resources :bios

  resources :image_sliders

  devise_for :users

  get "static_pages/admin"
  get "static_pages/landing"
  get "static_pages/kicker_list"
  resources :point_after_attempts

  resources :field_goals

  resources :punts

  resources :kickoffs

  resources :highlights

  devise_scope :user do
    get 'register', to: "devise/registrations#new", as: :register
    get 'login', to: "devise/sessions#new", as: :login
    get 'logout', to: "devise/sessions#destroy", as: :logout
  end

  root :to => 'static_pages#landing'

end

app/models/reference.rb
class Reference < ActiveRecord::Base
  attr_accessible :reference_email, :reference_name, :reference_phone, :reference_title
end

app/controllers/references_controller.rb
class ReferencesController < ApplicationController
  # GET /references
  # GET /references.json
  def index
    @references = Reference.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @references }
    end
  end

  # GET /references/1
  # GET /references/1.json
  def show
    @reference = Reference.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reference }
    end
  end

  # GET /references/new
  # GET /references/new.json
  def new
    @reference = Reference.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @reference }
    end
  end

  # GET /references/1/edit
  def edit
    @reference = Reference.find(params[:id])
  end

  # POST /references
  # POST /references.json
  def create
    @reference = Reference.new(params[:reference])

    respond_to do |format|
      if @reference.save
        format.html { redirect_to @reference, notice: 'Reference was successfully created.' }
        format.json { render json: @reference, status: :created, location: @reference }
      else
        format.html { render action: "new" }
        format.json { render json: @reference.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /references/1
  # PUT /references/1.json
  def update
    @reference = Reference.find(params[:id])

    respond_to do |format|
      if @reference.update_attributes(params[:reference])
        format.html { redirect_to @reference, notice: 'Reference was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @reference.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /references/1
  # DELETE /references/1.json
  def destroy
    @reference = Reference.find(params[:id])
    @reference.destroy

    respond_to do |format|
      format.html { redirect_to references_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/references_helper.rb
module ReferencesHelper
end

app/views/references/_form.html.erb
<% if user_signed_in? %>
<%= simple_form_for(@reference) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :reference_name %>
    <%= f.input :reference_title %>
    <%= f.input :reference_email %>
    <%= f.input :reference_phone %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class=> "button expand" %>
  </div>
<% end %>
<% else %>
<p class="label alert">You must be logged in to add or edit Field Goals.</p>
<% end %>

app/views/references/edit.html.erb
<div class="row">
	<div class="large-6 medium-8 columns medium-centered large-centered">
		<div class="panel">
			<h1>Edit <small>Reference</small></h1>
			<%= render 'form' %>
		</div>
		<%= link_to 'Show', @reference, :class=> "button secondary" %>
		<%= link_to 'Back', references_path, :class=> "button secondary" %>
	</div>
</div>

app/views/references/index.html.erb
<div class="row">
  <div class="large12 columns">
    <h1>References</h1>

    <table>
      <thead>
        <tr>
          <th>Reference name</th>
          <th>Reference title</th>
          <th>Reference email</th>
          <th>Reference phone</th>
          <% if user_signed_in? %>
          <th></th>
          <th></th>
          <% end %>
        </tr>
      </thead>

      <tbody>
        <% @references.each do |reference| %>
          <tr>
            <td><%= reference.reference_name %></td>
            <td><%= reference.reference_title %></td>
            <td><a href="mailto:<%= reference.reference_email %>"><%= reference.reference_email %></a></td>
            <td><a href="tel:<%= reference.reference_phone %>"><%= reference.reference_phone %></a></td>
            <% if user_signed_in? %>
            <td><%= link_to raw('<i class="fa fa-pencil"></i>'), edit_reference_path(reference), :class => "button tiny expand" %></td>
            <td><%= link_to raw('<i class="fa fa-times-circle"></i>'), reference, method: :delete, data: { confirm: 'Are you sure?' }, :class => "button tiny expand" %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>


    <%= link_to 'New Reference', new_reference_path, :class=> "button secondary" %>
  </div>
</div>

app/views/references/new.html.erb
<div class="row">
	<div class="large-6 medium-8 columns medium-centered large-centered">
		<div class="panel">
			<h1>New <small>Reference</small></h1>
			<%= render 'form' %>
		</div>
		<%= link_to 'Back', references_path, :class=> "button secondary" %>
	</div>
</div>

app/views/references/show.html.erb
<div class="row">
	<div class="large-12 columns">
		<div class="panel">
			<h1>Reference <small>Submitted</small></h1>
			<p><strong><%= @reference.reference_title %> <%= @reference.reference_name %></strong> has been submitted.</p>
			<p>Email: <%= @reference.reference_email %></p>
			<p>Phone: <%= @reference.reference_phone %></p>

			<%= link_to 'Edit', edit_reference_path(@reference), :class => "button secondary" %>
			<%= link_to 'Back to Bio', bio_path, :class => "button secondary" %>
		</div>
	</div>
</div>